### ISSUE TITLE
Professor Putricide - Regurgitated Ooze

### ISSUE THREAD

**Issue by algardo** [mnclaras/azerothcore-wotlk#14]
### Current Behaviour

Abomination -> [Regurgitated Ooze](https://db.rising-gods.de/?spell=70539) Spell (slow down spell) can be used on multiple times without cooldown. It must be 1 second. This is a problem because if you have enough energy to use it two times, and use the spell two or more times, it will be casted twice.

### Expected Blizzlike Behaviour

Regurgitated Ooze should have cooldown between casts: 1 second.

### Steps to reproduce the problem

1. Enter with 3 characters on ICC and reach Professor Putricide.
2. Attack the boss with one character and take abomination with the other.
3. Take 90+ energy with the abomination.
4. Cast Regurgitated Ooze and you will notice that it does not have Cooldown. You can basically spam it and drain all your energy

### Extra Notes

Videos from retail:
https://www.youtube.com/watch?v=uCLrlyyXD6I&ab_channel=Ciderhelm
https://www.youtube.com/watch?v=pllYT5du93I&ab_channel=christian
https://www.youtube.com/watch?v=hT4C_3RvtIU&ab_channel=TribunalXHunter
https://www.youtube.com/watch?v=v9lcgcdz19Y&ab_channel=tmcweld

### AC rev. hash/commit

-

### Operating system

Ubuntu

**Comment by UltraNix** [comment]
@algardo I can't reproduce it. The spell has 1 sec cooldown.

**Comment by algardo** [comment]
@UltraNix this is what is happening in our server: 
https://gyazo.com/68f1ec08c79e41e996fc1f998e5ba80e

You can throw it 2 times because it has no real gcd, so sometimes you waste all your energy with the abomination
